/** Builds a clean, readable plain-text report from analysis results. */
export function buildReportText(results, meta = {}) {
  const { fileName = 'Resume', analyzedAt = new Date() } = meta
  const lines = []

  lines.push('==============================================')
  lines.push('        ATS RESUME SCORE CHECKER REPORT')
  lines.push('==============================================')
  lines.push('')
  lines.push(`Resume File: ${fileName}`)
  lines.push(`Analyzed On: ${analyzedAt.toLocaleString()}`)
  lines.push('')
  lines.push(`ATS SCORE: ${results.atsScore} / 100  (${results.matchLevel})`)
  lines.push('')
  lines.push('--- SCORE BREAKDOWN ---')
  lines.push(`Skills Match:     ${results.breakdown.skillsMatchPercent}%`)
  lines.push(`Keyword Match:    ${results.breakdown.keywordMatchPercent}%`)
  lines.push(`Education Match:  ${results.breakdown.educationMatchPercent}%`)
  lines.push(`Experience Match: ${results.breakdown.experienceMatchPercent}%`)
  lines.push('')

  lines.push('--- SKILLS FOUND ---')
  lines.push(results.skillsFound.length ? results.skillsFound.join(', ') : 'None detected')
  lines.push('')

  lines.push('--- SKILLS MISSING ---')
  lines.push(results.skillsMissing.length ? results.skillsMissing.join(', ') : 'None — great coverage!')
  lines.push('')

  lines.push('--- MATCHED KEYWORDS ---')
  lines.push(results.matchedKeywords.length ? results.matchedKeywords.join(', ') : 'None detected')
  lines.push('')

  lines.push('--- MISSING KEYWORDS ---')
  lines.push(results.missingKeywords.length ? results.missingKeywords.join(', ') : 'None — great coverage!')
  lines.push('')

  lines.push('--- RESUME STRENGTHS ---')
  results.strengths.forEach((s, i) => lines.push(`${i + 1}. ${s}`))
  lines.push('')

  lines.push('--- RESUME WEAKNESSES ---')
  results.weaknesses.forEach((w, i) => lines.push(`${i + 1}. ${w}`))
  lines.push('')

  lines.push('--- IMPROVEMENT SUGGESTIONS ---')
  results.suggestions.forEach((s, i) => lines.push(`${i + 1}. ${s}`))
  lines.push('')

  lines.push('--- HIRING RECOMMENDATION ---')
  lines.push(results.hiringRecommendation)
  lines.push('')
  lines.push('==============================================')
  lines.push('Generated by ATS Resume Score Checker')
  lines.push('Built for Digital Heroes — https://digitalheroesco.com')
  lines.push('==============================================')

  return lines.join('\n')
}

/** Triggers a browser download of the report as a .txt file. */
export function downloadReportAsTxt(results, meta = {}) {
  const text = buildReportText(results, meta)
  const blob = new Blob([text], { type: 'text/plain;charset=utf-8' })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = 'ATS_Resume_Report.txt'
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
  URL.revokeObjectURL(url)
}

/** Copies the report text to the clipboard. Returns a promise<boolean>. */
export async function copyReportToClipboard(results, meta = {}) {
  const text = buildReportText(results, meta)
  try {
    await navigator.clipboard.writeText(text)
    return true
  } catch (err) {
    console.error('Clipboard copy failed:', err)
    return false
  }
}
